name: ATML

channels: 
  - conda-forge
  - defaults 
  
dependencies:
  - pip:
    - numpy==1.19.1
    - scipy==1.5.1
    - pyarmor==6.3.3
    - cryptography==3.0
    - pyglet==1.3.2
    - gym==0.12.5
    - Box2D==2.3.10
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==1.6.0
    - matplotlib==3.3.2
  - jupyter==1.0.0
  - jupyterlab==3.3.3 
  - ipykernel==5.5.5

# add these to also create jupyter notebooks
#   - jupyter==1.0.0
#   - jupyterlab==3.3.3
#   - ipykernel==5.5.5

# conda env create -f environment.yml
# conda env update --file environment.yml --prune
# conda remove --name new_env --all
# conda info --envs










